#!/bin/bash
# Setup script for google-1

# Check for ffmpeg installation
if ! command -v ffmpeg >/dev/null 2>&1; then
    sudo apt-get install ffmpeg
fi

# Install/ upgrade python dependency
pip2 install --user --upgrade ffmpy
pip2 install --user --upgrade google-cloud-speech==0.27.0