#!/bin/bash
# Setup script for lvcsr-1701

CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
N_PROC=$(nproc --all)
. $HOME/.bashrc

# Kaldi installation
function install_kaldi {
    # clone repo in $HOME/kaldi
    cd $HOME
    if [ -d kaldi ]; then
        cd kaldi
        git fetch
        git pull
    else
        git clone https://github.com/kaldi-asr/kaldi.git
        cd kaldi
    fi
    # latest 'stable' release
    git checkout 5.1 || { echo "git operations failed"; exit 1; }

    # tools
    cd tools
    no_deps=0
    # check dependencies, parse the results to install deps
    sudo apt install g++
    while [ $no_deps -eq 0 ]; do
        deps=$(extras/check_dependencies.sh | grep 'sudo apt-get install' | cut -d' ' -f5- | xargs) || exit 1
        if [ -z "$deps" ]; then
            no_deps=1
        else
            sudo apt install $deps
        fi
    done
    make -j $N_PROC || { echo "make failed for tools"; exit 1; }

    # src
    cd ../src
    ./configure --shared
    make depend -j $N_PROC || { echo "make depend failed for src"; exit 1; }
    make -j $N_PROC || { echo "make failed for src"; exit 1; }

    # add to environment variable
    echo "export KALDI_ROOT=$HOME/kaldi" >> $HOME/.bashrc
    KALDI_ROOT=$HOME/kaldi
    export KALDI_ROOT=$HOME/kaldi
    echo "Kaldi successfully installed"
}

# Sequitur installation
function install_sequitur {
    cd $KALDI_ROOT/tools
    if [ -f env.sh ]; then
        echo "Sequitur already installed"
    else
        # install deps
        sudo apt install python-pip swig
        pip2 install --user --upgrade numpy
        extras/install_sequitur.sh || { echo "installation failed for sequitur"; exit 1; }
        echo "Sequitur successfully installed"
    fi
}

# Install LVCSR systems
# (C) Xu Haihua, NTU
cd $CUR_DIR
if [ ! -d systems ]; then
    if [ ! -f $HOME/systems.tar.gz ]; then
        echo "Getting LVCSR system from NTU cluster (155.69.146.215)..."
        echo "If you do not have access to this cluster, the next step would fail automatically."
        read -p "Username: " username
        scp $username@155.69.146.215:/home/nhanh/work/downloads/systems.tar.gz $HOME/systems.tar.gz || { echo "failed when downloading system"; exit 1; }
    fi
    tar -xvf $HOME/systems.tar.gz || { echo "failed when extracting system"; exit 1; }
    rm $HOME/systems.tar.gz
    echo "LVCSR system successfully installed"
else
    echo "LVCSR system already installed"
fi

# Check for kaldi installation using env
if [ -z "$KALDI_ROOT" ]; then
    install_kaldi || exit 1
else
    echo "Kaldi already installed"
fi

# Install sequitur
install_sequitur
