#!/bin/bash
# Setup script for lvcsr-1701

N_PROC=$(nproc --all)
. $HOME/.bashrc

# Kaldi installation
function install_kaldi {
    # clone repo in $HOME/kaldi
    cd $HOME
    if [ -d kaldi ]; then
        cd kaldi
        git fetch
        git pull
    else
        git clone https://github.com/kaldi-asr/kaldi.git
        cd kaldi
    fi
    # latest 'stable' release
    git checkout 5.1 || { echo "git operations failed"; exit 1; }

    # tools
    cd tools
    no_deps=0
    # check dependencies, parse the results to install deps
    sudo apt-get install g++
    while [ $no_deps -eq 0 ]; do
        deps=$(extras/check_dependencies.sh | grep 'sudo apt-get install' | cut -d' ' -f5- | xargs) || exit 1
        if [ -z "$deps" ]; then
            no_deps=1
        else
            sudo apt-get install $deps
        fi
    done
    make -j $N_PROC || { echo "make failed for tools"; exit 1; }

    # src
    cd ../src
    ./configure --shared
    make depend -j $N_PROC || { echo "make depend failed for src"; exit 1; }
    make -j $N_PROC || { echo "make failed for src"; exit 1; }

    # add to environment variable
    echo "export KALDI_ROOT=$HOME/kaldi" >> $HOME/.bashrc
    KALDI_ROOT=$HOME/kaldi
    export KALDI_ROOT=$HOME/kaldi
}

# Sequitur installation
function install_sequitur {
    cd $KALDI_ROOT/tools
    if [ -f env.sh ]; then
        echo "Sequitur already installed"
    else
        # install deps
        sudo apt-get install python-pip swig
        pip2 install --user --upgrade numpy
        extras/install_sequitur.sh || { echo "installation failed for sequitur"; exit 1; }
    fi
}

# Check for kaldi installation using env
if [ -z "$KALDI_ROOT" ]; then
    install_kaldi || exit 1
fi

# Install sequitur
install_sequitur
