#!/bin/sh
# Setup script for resample-1.0

# Check for ffmpeg installation
if ! command -v ffmpeg >/dev/null 2>&1; then
    sudo apt-get install ffmpeg
fi

# Install/ upgrade python dependency
pip2 install --user --upgrade ffmpy